### PR TITLE
Remove globbing from tests

### PR DESCRIPTION
**Pull request by csegarragonz**
This had been a long standing to-do that I address here. Remove the globbing for files and add them manually instead.

### CODE REVIEW

**Comment by Shillaker** [comment]
Can you remind me again what the problem with globbing is? This looks verbose and easy to miss tests by accident.

**Comment by csegarragonz** [comment]
> Can you remind me again what the problem with globbing is? This looks verbose and easy to miss tests by accident.

@Shillaker see the `Note` in the [CMake docs](https://cmake.org/cmake/help/latest/command/file.html#filesystem). In my experience, the `Note` translates to having to remember to re-run `CMake` for the globbed file list to be re-generated, otherwise CMake has no way of knowing what files have changes. This is counter-intuitive, as it defeats a bit the purpose of globbing. On the other hand, adding the test names is more verbose, but once you get used to it you don't forget to add new files, and don't need to explicitly run `CMake` again.

**Comment by Shillaker** [comment]
Hmm, I'm still worried that somebody will accidentally delete a test file or forget to add one. Is it possible to have a catch-all glob at the end as well or is that really gross?

**Comment by csegarragonz** [comment]
Why is this a problem? AFAICT we list sources by name everywhere else in the the repo, why should tests be any different?

**Comment by Shillaker** [comment]
If we leave sources out in the rest of the codebase, something will fail to compile (unless the code in that file isn't used anywhere, in which case it should be deleted). Tests are at the end of the include chain, i.e. they are not included by any other files implicitly or explicitly, so it's impossible to tell whether all of them are being run.

**Review by Shillaker — APPROVED** [review]

**Pull request merged**
